-- Seed data for the Shelf Help Assistant database
-- This file contains sample data for development and testing

-- Sample books data
INSERT INTO public.books (id, title, author, isbn_13, publisher, publication_date, page_count, description, format, genres, tags) VALUES
(
    '550e8400-e29b-41d4-a716-446655440001',
    'The Pragmatic Programmer',
    'Andrew Hunt, David Thomas',
    '9780135957059',
    'Addison-Wesley Professional',
    '2019-09-13',
    352,
    'The Pragmatic Programmer illustrates the best approaches and major pitfalls of many different aspects of software development.',
    'physical',
    ARRAY['Programming', 'Technology', 'Software Engineering'],
    ARRAY['career', 'best-practices', 'software-development']
),
(
    '550e8400-e29b-41d4-a716-446655440002',
    'Clean Code',
    'Robert C. Martin',
    '9780132350884',
    'Prentice Hall',
    '2008-08-01',
    464,
    'A Handbook of Agile Software Craftsmanship. Even bad code can function. But if code isn''t clean, it can bring a development organization to its knees.',
    'physical',
    ARRAY['Programming', 'Software Engineering'],
    ARRAY['clean-code', 'refactoring', 'programming']
),
(
    '550e8400-e29b-41d4-a716-446655440003',
    'Dune',
    'Frank Herbert',
    '9780441172719',
    'Ace Books',
    '1965-08-01',
    688,
    'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.',
    'physical',
    ARRAY['Science Fiction', 'Fantasy', 'Adventure'],
    ARRAY['space-opera', 'politics', 'ecology']
),
(
    '550e8400-e29b-41d4-a716-446655440004',
    'The Design of Everyday Things',
    'Don Norman',
    '9780465050659',
    'Basic Books',
    '2013-11-05',
    368,
    'Design doesn''t have to complicated, which is why this guide to human-centered design shows that usability is just as important as aesthetics.',
    'ebook',
    ARRAY['Design', 'Psychology', 'Technology'],
    ARRAY['user-experience', 'design-principles', 'usability']
),
(
    '550e8400-e29b-41d4-a716-446655440005',
    'Atomic Habits',
    'James Clear',
    '9780735211292',
    'Avery',
    '2018-10-16',
    320,
    'An Easy & Proven Way to Build Good Habits & Break Bad Ones. Transform your life with tiny changes in behavior that add up to remarkable results.',
    'physical',
    ARRAY['Self-Help', 'Psychology', 'Productivity'],
    ARRAY['habits', 'personal-development', 'behavior-change']
),
(
    '550e8400-e29b-41d4-a716-446655440006',
    'Sapiens: A Brief History of Humankind',
    'Yuval Noah Harari',
    '9780062316110',
    'Harper',
    '2015-02-10',
    443,
    'From a renowned historian comes a groundbreaking narrative of humanity''s creation and evolution that explores the ways in which biology and history have defined us.',
    'audiobook',
    ARRAY['History', 'Anthropology', 'Philosophy'],
    ARRAY['human-evolution', 'civilization', 'anthropology']
);

-- Sample user profile (this would normally be created when a user signs up)
-- Note: In a real application, this would be handled by the authentication flow
-- The UUID here should match a user in auth.users table

-- Sample reading sessions
-- Note: These would be created after users actually exist in the system
-- For now, they're commented out as they require valid user_id references

-- INSERT INTO public.reading_sessions (user_id, book_id, status, start_date, end_date, current_page, rating, review, is_favorite, reading_goal_year) VALUES
-- (
--     'user-uuid-here',
--     '550e8400-e29b-41d4-a716-446655440001',
--     'completed',
--     '2024-01-15',
--     '2024-02-10',
--     352,
--     5,
--     'Excellent book for any programmer. Changed how I think about code quality and professional development.',
--     true,
--     2024
-- ),
-- (
--     'user-uuid-here',
--     '550e8400-e29b-41d4-a716-446655440002',
--     'in_progress',
--     '2024-02-15',
--     NULL,
--     150,
--     NULL,
--     'Reading this alongside The Pragmatic Programmer. Great insights on writing maintainable code.',
--     false,
--     2024
-- );

-- Sample book embeddings would be generated by the AI system
-- These are placeholder entries to demonstrate the structure
-- INSERT INTO public.book_embeddings (book_id, content_type, content_text, metadata) VALUES
-- (
--     '550e8400-e29b-41d4-a716-446655440001',
--     'description',
--     'The Pragmatic Programmer illustrates the best approaches and major pitfalls of many different aspects of software development.',
--     '{"source": "description", "processed_at": "2024-01-01T00:00:00Z"}'
-- );

-- Function to add sample user data (to be called after user registration)
CREATE OR REPLACE FUNCTION public.add_sample_user_data(user_uuid uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Insert sample user profile
    INSERT INTO public.user_profiles (id, display_name, preferred_language, reading_goal_books_per_year)
    VALUES (user_uuid, 'Sample User', 'en', 24)
    ON CONFLICT (id) DO NOTHING;

    -- Insert sample reading sessions
    INSERT INTO public.reading_sessions (user_id, book_id, status, start_date, end_date, current_page, rating, review, is_favorite, reading_goal_year) VALUES
    (
        user_uuid,
        '550e8400-e29b-41d4-a716-446655440001',
        'completed',
        '2024-01-15',
        '2024-02-10',
        352,
        5,
        'Excellent book for any programmer. Changed how I think about code quality and professional development.',
        true,
        2024
    ),
    (
        user_uuid,
        '550e8400-e29b-41d4-a716-446655440003',
        'in_progress',
        '2024-02-15',
        NULL,
        200,
        NULL,
        'Epic science fiction masterpiece. The world-building is incredible.',
        false,
        2024
    ),
    (
        user_uuid,
        '550e8400-e29b-41d4-a716-446655440005',
        'completed',
        '2024-03-01',
        '2024-03-20',
        320,
        4,
        'Practical approach to habit formation. Implementing the 1% better concept.',
        true,
        2024
    )
    ON CONFLICT (user_id, book_id, status) DO NOTHING;
END;
$$;

-- Grant necessary permissions
GRANT EXECUTE ON FUNCTION public.add_sample_user_data(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_reading_recommendations(uuid, int) TO authenticated;

-- Grant permissions for search function based on pgvector availability
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pgvector') THEN
        GRANT EXECUTE ON FUNCTION public.search_books_by_embedding(vector, float, int) TO authenticated;
    ELSE
        GRANT EXECUTE ON FUNCTION public.search_books_by_embedding(text, float, int) TO authenticated;
    END IF;
END $$;